### PR TITLE
Batch loading

### PR DESCRIPTION
**Pull request by egpbos**
This PR adds the possibility to load gt3x files in batches. This can be used to circumvent issues with running out of memory. It thus provides a solution to the problems discussed in https://github.com/wadpac/GGIR/issues/87.

The solution is simply to add three parameters:

1. `use_batching` is a boolean that switches on batching mode. Note that this also disables imputeZeroes, even if it is set to `TRUE` by the user. This is because the combination of these two options would add a lot of extra bookkeeping to the code. Apart from going beyond the scope of this PR, I thought it also might not be desired from a maintainability point of view.
2. `batch_begin` is the batch index (an index running over the activity records in the file) at which the requested batch should start.
3. `batch_end` is the index of the last batch that's included in the batch.

These parameters are passed on to the C++ implementation that has been updated to accomodate for them. It still scans the file, which is unavoidable lacking an index of the file's records. However, it keeps a counter of the activity records (the "batches") and starts adding them to the output matrix once it reaches `batch_begin` and stops adding them when it passed `batch_end`, at which point the `while` loop is also stopped, saving a bit of time (more for early batches, less for later batches, since it still has to scan the whole file up until the batch; however, since the goal of this modification is fitting the operation into memory, saving time is just an added bonus, not the main priority).

This PR was designed together with @vincentvanhees.

### CODE REVIEW

**Comment by vincentvanhees** [comment]
Just to clarify that I asked @egpbos to ignore the impute zeroes option as I prefer to impute the missing data outside read.gt3x for two reasons:

1. Imputing data by zeros in all three axes is physically not meaningful. An accelerometer should be capturing gravitational acceleration when not moving, not zeros. A better imputation would be the last recorded gravitational component captured before the missing data period, or if unavailable the one captured after the missing data period.
2. I may want to explore imputing gt3x missing data at feature level (e.g. 5 seconds or 1 minute) inside GGIR as opposed to imputing the raw data. This to avoid getting into memory problems if there would be large multi-day time gaps.

I have tested this PR in a couple of .gt3x files with and without time gaps caused by sleep.mode option.

**Comment by vincentvanhees** [comment]
To showcase the impact of this PR, please find below a little demo:

### Without batching, reading in entire file in one go:

My Virtual Machine freezes and I had to reset it.

gt3x_without_batching

### Reading in the data with 1 day per batch, and removing the batch before loading in the next batch:

All goes smooth and I am able to read all the data.

gt3x_with_batching

R code used for batching:
```
fn = "/media/vincent/DATA/gt3xreading/long/long_test_file.gt3x"
library(read.gt3x)
N = 24*3600
M = 30
delta = rep(0, M)
i = 1
while (i > 0) {
  A =c()
  t0 = Sys.time()
  try(expr={
    A = read.gt3x(fn, asDataFrame = TRUE, use_batching = TRUE,
                  batch_begin = 1+((i-1)*N), batch_end = i*N)
  },silent=TRUE)
  t1 = Sys.time()
  delta[i] = round(difftime(t1, t0,units = "secs"), digits=2)
  print(paste(i, " ", delta[i]))
  if (length(A) == 0) {
    i = -1
  } else {
    print(paste0(A$time[1]," ",A$time[nrow(A)]))
    rm(A)
  }
  i = i + 1
}
```

**Comment by TuomoNieminen** [comment]
Good work, thanks!

Zeroes:
"Imputation" is a poor choice of wording; the rows with all zeroes represent missing values. The choice of all zeroes comes from ActiGraph, I believe, the idea was to be able to reproduce their csv files exactly.

I think it's fine that this solution, which aims for memory efficiency, will not include explicit missing data but rather leaves it missing.

The scope:
If I understand correctly, the implementation does not cover the old .gt3x formats. Is this correct? Do you have thoughts on this @muschellij2 ?

Documentation:
The docs related to the batch loading feature use the term "record". This could be clarified. I think in practise the batch indices corresponf to the indices of the seconds for which data was recorded, right?

**Comment by muschellij2** [comment]
I think a compelling use case would be good here.  I do believe this PR adds value, but the cost of breaking behavior may be a bit too high and could be refactored.

1.  The current behavior is that zeroes are where non-data exists in the data and would break a lot of current pipelines if changed.  I would caution heavily against this.
2. I think the argument of "extra bookkeeping to the code" would not be one to override an argument that was specified.
3. It may make more sense to take some of the internals out to a more generic function but leave `read.gt3x` without batching by default. 

What about one `batch_size` argument or a on-disk framework (that doesn't load all the data, such as hdf5/fst/ff) as an option?.  If that `batch_size` is `NULL` (or you could maybe set to be `Inf`) then you read the whole file in.  
I think start/end arguments may not be for the general user and may be a bit a bit non-intuitive as they are integers versus datetime objects.

Also, I do not think this covers the old formats.

**Comment by vincentvanhees** [comment]
Thanks guys for taking the time to look into this.

**In response to @TuomoNieminen:**

> Zeroes: "Imputation" is a poor choice of wording; the rows with all zeroes represent missing values. The choice of all zeroes comes from ActiGraph, I believe, the idea was to be able to reproduce their csv files exactly.

I understand and for that purpose read.gt3x is very valuable. However, my aim here is to avoid having to create ActiGraph .csv files and work with .gt3x files directly to save storage space and computing time.

> If I understand correctly, the implementation does not cover the old .gt3x formats. Is this correct? 

Correct, this does not cover the old .gt3x format. I am pushing this development for a client and they only have modern .gt3x data. I understand that also covering the old format would be nice, but my efforts are focused on my clients needs. If someone else stands up to sponsor expansion of this functionality to the old format then that would of course be nice.

> Documentation: The docs related to the batch loading feature use the term "record". This could be clarified. 

Agree, maybe the term "sample" is more in line with the rest of your documentation? **=> action point 1**

> I think in practise the batch indices corresponf to the indices of the seconds for which data was recorded, right?

Yes, correct. The batch indices are effectively seconds in the recording. This may need to be documented. **=> action point 2**

**In response to @muschellij2:**

> I think a compelling use case would be good here. 

The showcase I have given [above](https://github.com/THLfi/read.gt3x/pull/40#issuecomment-963977213) illustrates that gt3x.read causes R to crash when applied to 7 day 100 Hertz recordings on 8GB memory machines. Not all researchers have 16GB memory and some researchers may prefer to submit many 8GB jobs on a cluster rather than half as many 16GB jobs. The challenge is not only about loading the data, but also about having enough memory left after loading to process the data.

> I do believe this PR adds value, but the cost of breaking behavior may be a bit too high and could be refactored. The current behavior is that zeroes are where non-data exists in the data and would break a lot of current pipelines if changed. I would caution heavily against this.

The batch-loading is only used when explicitly asked for by the user, by which existing functionality does not break. Although, I can see your point that not adding zeros to the time gaps when in batch-mode is a discontinuation of expected functionality.

> I think the argument of "extra bookkeeping to the code" would not be one to override an argument that was specified.
It may make more sense to take some of the internals out to a more generic function but leave read.gt3x without batching by default. What about one batch_size argument or a on-disk framework (that doesn't load all the data, such as hdf5/fst/ff) as an option?. If that batch_size is NULL (or you could maybe set to be Inf) then you read the whole file in.

I agree on your point about using only `batch_end` default Inf, and `batch_begin` by default 0 or 1, to remove the need for `use_batching` argument. **=> action point 3**

Note that the code is currently not batching by default. Converting to hdf5 or any other file format still require machines with >8GB memory to make that conversion and data will still have to be archived in two different formats, which is what this PR tries to avoid. Or maybe I am misunderstanding your point.

> I think start/end arguments may not be for the general user and may be a bit a bit non-intuitive as they are integers versus datetime objects.

Yes, these are not for the general user but will be used by other software such as GGIR. Inside GGIR I have code that takes care of loading and handling the data from all sensor brands and formats in batches out of sight from the user. This approach of using a start/end data page or batch would be in line with how GGIR reads AX3 .cwa and GENEA .bin files, and how GENEAread reads GENEactiv .bin files. By keeping the approach consistent with those other file reading functions it will be easier to integrate them. For example, if someone has a new memory hungry algorithm then it would now be easy for them to write a single wrapper function to load files from any accelerometer format in batches and apply the algorithm to the data. 

The start/end argument reflects seconds of time in the recording (see my response to Tuomo). I agree that it could be valuable to extent this functionality to also allow for start/end timestamps, but that would have to be a future enhancement if it was up to me.  **=> future action point**

> Also, I do not think this covers the old formats.

Yes, it does not cover the old formats (see my response to Tuomo above).

**As a more general comment:** 
If we would not be able to agree on the approach taken even after additional minor edits, then one alternative solution could be that I make the current CRAN version of read.gt3x a dependency of GGIR, and add the modified code of read.gt3x.R and parseGT3X.cpp to the GGIR code and rename them to avoid namespace clashes. This is not ideal as it leads to code overlap between repositories, but if there is no other solution then that would be my plan B.

**Comment by muschellij2** [comment]
I don't know about GPL vs. EUPL, but the harvesting of code would require the licenses to make sure all is good with attribution and copyright.  

EDIT: didn't see action point 3 above but this paragraph is in agreement with your thoughts, but the warning is a necessity
I think that 3 arguments could be reduced to 2 with defaults for `batch_begin` and `batch_end` as both as `NULL` and `use_batching = !is.null(batch_begin) || !is.null(batch_end)`, and there **needs** to be a warning if `imputeZeroes = TRUE` and these are specified to ensure the user is alerted to the behavior change.  Then also it makes sense to set `batch_begin = 0L` if `!is.null(batch_end)` and to set `batch_end = Inf` if `!is.null(batch_begin)`.  Thus, you can set eitehr beginning or ending (and it does smart guessing of 0/Inf) and if you specify either, then batching is turned on.  For example, if you set batch_begin/end and don't set `use_batching = TRUE` what happens?

If you're going to go through with 3 arguments, I think a test for all 5 combinations (T/F for batching) and specifying begin/end would be sufficient (default already tested).

**Comment by vincentvanhees** [comment]
> I don't know about GPL vs. EUPL, but the harvesting of code would require the licenses to make sure all is good with attribution and copyright.

I fully agree, GGIR is LGPL and my quick understanding is that both are permissive licenses that should allow for this... but let's hope we do not have to take that road.

Perfect, I will have a chat with @egpbos how we can address these action points in the upcoming week(s).

**Comment by muschellij2** [comment]
Does `get_n_samples` line up with the  maximum of `batch_end`?

https://github.com/THLfi/read.gt3x/blob/49d02c3401b5ce8846d7ac031486af1656e334d7/R/utils.R#L195

**Comment by vincentvanhees** [comment]
I have now committed the following changes:

1. Updated documentation for `parseGT3X.cpp` to clarify that batches are defined in seconds in time relative to start of raw non-imputed recording. This avoids having to use terms like record or sample that would clash with existing code. (**Action points 1 and 2** above)
2. Argument `use_batching` has been omitted from `parseGT3X.cpp`. Instead `parseGT3X.cpp` sets `use_batching` as a constant boolean at the top with default value `false`, which is updated to `true` if `batch_end` is larger than zero. (**Action point 3** above)
3. Unit test added for scenario when user forgets to specify `batch_begin` or `batch_end`.
4. Rcpp warning added to inform user when `batch_begin` greater than `batch_end`.

Clarification for why I did not do two other suggestions:

- I have not incorporated the suggestion by @muschellij2 to let the maximum of `batch_end` line up with `get_n_samples` because `get_n_samples` includes time gaps which is not compatible with `batch_end` which excludes time gaps.
- Instead of `batch_end = Inf` I now use `batch_end = 0`, because `batch_end` is an unsigned 32 integer, which does not allow for `Inf` value assignment. Therefore, using 0 as default seems most practical.

**Comment by vincentvanhees** [comment]
I appreciate that you may not have had the time to look into this. As it is important to me that this functionality becomes available to the GGIR users, I will now pursue my alternative plan which is to add the new functionality to GGIR directly. Once you have had time to merge this PR and push it to CRAN I will remove it from GGIR as I have no interest in 'harvesting' your code. One advantage of this approach for you is that the new functionality can extensively be tested without causing you headaches in relation to read.gt3x.

#### EDIT: Given John's reply below, I am now postponing this to January or abandon the plan in case Tuomo indicates that a new read.gt3x CRAN release is feasible in January.

**License compatibility:**
EUPL as used by read.gt3x and LGPL as used by GGIR are compatible: https://joinup.ec.europa.eu/collection/eupl/introduction-eupl-licence

**Merging process:**
To merge the code I will adhere to Hadley Wickham's guidelines https://r-pkgs.org/license.html. More specifically I will make the following updates to GGIR:

1. Add the CRAN version of read.gt3x as a dependency, because I will still use some of the read.gt3x functions directly.
2. Copy the modified version of read.gt3x.R and parseGT3X.cpp to GGIR and rename them to read.gt3x_ggir.R and parseGT3X_ggir.cpp to avoid namespace clashes with the original.
3. Add your names to the GGIR author list in the DESCRIPTION file with role "cph" (copyright holder), with a [comment](https://r-pkgs.org/description.html) stating that you hold the copyright for those two functions with minor edits from Patrick and me.
4. Add LICENSE.note file similar to https://github.com/r-lib/diffviewer/blob/main/LICENSE.note
5. Add full copy of EUPL and LGPL licenses in a new to be created inst/licenses folder.
6. Add line at the top of the two functions: "Copyright (2021): Tuomo Nieminen, and John Muschelli; license: EUPL, see LICENSE.note file for details"
7. Add warnings in the documentation and in the code that read.gt3x_ggir.R and parseGT3X_ggir.cpp may be temporary and users are urged not to build direct dependencies on read.gt3x_ggir.R or parseGT3X_ggir.cpp as they will be deprecated shortly after they has been adopted by read.gt3x.

**My timeline:**
-Do the above and include in GitHub-only release of GGIR => ~~Next week~~ January 2022
- Integrate in a new GGIR CRAN release. => Second half of January

If you have any questions or concerns then let me know.

**Comment by muschellij2** [comment]
Do you have any comments on the fails for ubuntu?

**Comment by vincentvanhees** [comment]
I am not able to see the error log when I click on details, but will have a look whether I can reproduce the failing test in Ubuntu locally in the upcoming days.

**Comment by vincentvanhees** [comment]
I am not able to reproduce the fail here on my local Ubuntu 20.04 machine. Note that the build fail for the master branch occurred when Tuomo merged PR #39 on 16th of November. Possibly the fail does not relate to that specific PR but to the problems RStudio package manager has been having, see: https://status.rstudio.com.

Early December their issues caused all GitHub Action runs for R packages in Ubuntu to fail. That was fixed on 11th of December, but maybe their status update from 17 December 2021 indicates that there are still some issues. To investigate this, I just re-ran the GitHub Actions workflow for a repository that I have full access to and all Ubuntu checks pass. This sounds to me like it should be working now.

EDIT: Rstudio made another [upgrade](https://status.rstudio.com) to the package manager yesterday (22 December 2021), and the Ubuntu fails should be fixed now.

Would you mind re-running the GitHub Actions workflow for the THLfi/read.gt3x Master branch? If that turns green then maybe it truly was related to Rstudio package manager. If not, it is either the merged PR #39, or a combination of both PR #39 and RStudio package manager.

**Comment by muschellij2** [comment]
@TuomoNieminen - looks good to me with the tests.  I still don't love the batches given by the start end integers and maybe not time or at least *estimate* the number of batches possible (so it can be looped over or programmatically defined), but unit tests are there with documentation, so can't ask for much more than that IMO.

**Comment by TuomoNieminen** [comment]
With regards to the Ubuntu checks. As I was not able to reproduce the issues on my ubuntu 16.04 installation locally, I have assumed that the issue is related to the automated process and not the package code. I should have commented on this. I interpret that this hypothesis has now been verified. Is this correct?

**Comment by TuomoNieminen** [comment]
I have two requests.

Clarify the documentation of batch_begin and batch_end parameters. 
- Specify what happens with the default options. 
- Specify requirements for sensible behaviour (e.g. non-negativeness or batch_end > batch_begin). 
- Note what happens in cases where requirements are not met.

Produce either an example of usage in the read.gt3x function docs, or create a vignette which demonstrates batching.

**Comment by vincentvanhees** [comment]
Thanks, I have now added:
- A new vignette [vignettes/batch_loading_gt3x.Rmd](https://github.com/THLfi/read.gt3x/blob/60525e6eea7d765733bd13f71a59f0dc01ec6c69/vignettes/batch_loading_gt3x.Rmd) describing purpose, usage and behaviour of the batch-loading functionality.
- A reference from the read.gt3x documentation to the new vignette [(link to specific line)](https://github.com/THLfi/read.gt3x/blob/60525e6eea7d765733bd13f71a59f0dc01ec6c69/man/read.gt3x.Rd#L35).
- New line in NEWS.Rd file to reflect this newly added batch-loading functionality.
- My name to the DESCRIPTION file.

**Comment by TuomoNieminen** [comment]
Thank you,

This looks good to me. Pulling it in.

**Pull request merged**
