### PR TITLE
Passes R CMD check

### PR DESCRIPTION
**Pull request by muschellij2**
Fixed the documentation so this should pass `R CMD check`.  The `gt3x_datapath` should not go to `~` (HOME) as this violates CRAN policies.  I've made it go to a temporary directory.  Should work fine now.

### CODE REVIEW

**Comment by TuomoNieminen** [comment]
Looks great, thanks!

I suppose the effect of using tempdir() will be that the sample data must be downloaded each time they are accessed. The earlier design made it so that the data would be locally available in future sessions. 

Anyway, I don't think this is a big loss so I like the change.

**Comment by muschellij2** [comment]
I believe the way I changed it is that the data will be downloaded to
tempdir/.read.gt3x-data when using gt3x_datapath, but otherwise everything
is in a temporary directory.
Best,
John

**Comment by muschellij2** [comment]
You can see passing at
https://travis-ci.com/muschellij2/read.gt3x/builds
[Travis build status](https://travis-ci.com/muschellij2/read.gt3x)
and https://ci.appveyor.com/project/muschellij2/read-gt3x
[AppVeyor build status](https://ci.appveyor.com/project/muschellij2/read-gt3x)

**Comment by TuomoNieminen** [comment]
I looked this over and see no issues. Great job. Very good that you have added more development technology and tests. Awsome that you were able to get the old version parsed as well. I'll merge this PR.

**Pull request merged**
